In [2]:
CHILDREN = 0
WEIGHT = 1

import sys

import pandas as pd
import numpy as np

from matplotlib import pyplot as plt
%matplotlib inline

from importlib import reload

trackml_path = '/home/ec2-user/SageMaker/TrackML'
if trackml_path not in sys.path:
    sys.path.append(trackml_path)
    
# from detector_grid import detector_grid
# reload(detector_grid)

In [3]:
detector = pd.read_csv('/home/ec2-user/SageMaker/efs/codalab_dataset/detector.csv')
detector = detector.loc[:, ['volume_id', 'layer_id', 'module_id', 'cx', 'cy', 'cz']]
detector.loc[:, 'cR'] = np.sqrt(
    detector.cx**2 +
    detector.cy**2 +
    detector.cz**2
)
detector.loc[:, 'ctheta'] = np.arctan2(detector.cx, detector.cy)
detector.loc[:, 'cphi'] = np.arccos(detector.cz/detector.cR)
print(detector.info())
detector.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18728 entries, 0 to 18727
Data columns (total 9 columns):
volume_id    18728 non-null int64
layer_id     18728 non-null int64
module_id    18728 non-null int64
cx           18728 non-null float64
cy           18728 non-null float64
cz           18728 non-null float64
cR           18728 non-null float64
ctheta       18728 non-null float64
cphi         18728 non-null float64
dtypes: float64(6), int64(3)
memory usage: 1.3 MB
None


volume_id  layer_id  module_id        cx        cy      cz           cR  \
0          7         2          1  -65.7965  -5.17830 -1502.5  1503.948884   
1          7         2          2 -139.8510  -6.46568 -1502.0  1508.510559   
2          7         2          3 -138.6570 -19.34190 -1498.0  1504.527791   
3          7         2          4  -64.1764 -15.40740 -1498.0  1499.453233   
4          7         2          5 -136.2810 -32.05310 -1502.0  1508.510495   

     ctheta      cphi  
0 -1.649336  3.097694  
1 -1.616996  3.048652  
2 -1.709397  3.048406  
3 -1.806416  3.097562  
4 -1.801796  3.048652

In [4]:
print(detector.cR.min(), detector.cR.max())
print(detector.ctheta.min(), detector.ctheta.max())
print(detector.cphi.min(), detector.cphi.max())

47.25526949012565 3101.990480061794
-3.141592653589793 3.141592653589793
0.04389853636220709 3.097694117227586


In [5]:
np.linspace(-np.pi, np.pi, 10)

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [6]:
np.geomspace(1, 5, 10)

array([1.        , 1.19581317, 1.42996915, 1.70997595, 2.04481177,
       2.44521285, 2.92401774, 3.49657893, 4.18125515, 5.        ])

In [8]:
nbins_R = 10
nbins_z = 10
nbins_phi = 10

R_min, R_max = 30., 1030.
z_min, z_max = -2956., 2956.
phi_min, phi_max = -np.pi, np.pi

phi_grid = np.linspace(phi_min, phi_max, nbins_phi)

# pos_z_grid = np.geomspace()

In [17]:
v = np.array([1., 2., 3.])
v /= np.linalg.norm(v)
v.argmax()

2

In [13]:
d = {x: 1}

TypeError: unhashable type: 'numpy.ndarray'

In [18]:
v

array([0.26726124, 0.53452248, 0.80178373])

In [19]:
v[[0, 1]]

array([0.26726124, 0.53452248])

In [22]:
np.tile(v, 2)

array([0.26726124, 0.53452248, 0.80178373, 0.26726124, 0.53452248,
       0.80178373])

In [30]:
np.tile(v, 2, axis=1)

TypeError: tile() got an unexpected keyword argument 'axis'

In [32]:
cos_grid = np.cos(np.linspace(-np.pi, 0, 10))
cos_grid

array([-1.        , -0.93969262, -0.76604444, -0.5       , -0.17364818,
        0.17364818,  0.5       ,  0.76604444,  0.93969262,  1.        ])

In [34]:
np.digitize(v[[0, 1]], cos_grid)

array([6, 7])